/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import Classes.Connect;
import java.awt.Color;
import java.text.SimpleDateFormat;  
import java.util.Date;   
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;


/**
 *
 * @author dsoto
 */
public class Customer_Info extends javax.swing.JFrame {

   String user;
   public static String customer_name="";
   public static int id_device;
    int ID=0;
     int ID2=0;
    DefaultTableModel model=new DefaultTableModel();
    
    public Customer_Info() {
        initComponents();
        this.setLocationRelativeTo(null);
        user=Logo.user;
        ID=LOG_USER.ID;
        ID2=LOG_USER.ID;
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);    
        ImageIcon wallpaper= new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon ic=new ImageIcon(wallpaper.getImage().getScaledInstance(jl_wallpaper.getWidth(), jl_wallpaper.getHeight(),Image.SCALE_DEFAULT));
        jl_wallpaper.setIcon(ic);
        this.repaint();
        
        try{
            Connection cn=Connect.Cnnct();
            PreparedStatement ps=cn.prepareStatement("select nombre_cliente,mail_cliente,tel_cliente,dir_cliente,ultima_modificacion from clientes where id_cliente='" + ID +"'");
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
            customer_name=rs.getString("nombre_cliente");
            jt_name.setText(rs.getString("nombre_cliente"));
            jt_email.setText(rs.getString("mail_cliente"));
            jt_telephone.setText(rs.getString("tel_cliente"));
            jt_address.setText(rs.getString("dir_cliente"));
            jt_lastm.setText(rs.getString("ultima_modificacion"));
            }
            cn.close();
            
            
       }
        catch(SQLException e){
            jt_name.setBackground(Color.red);
            jt_email.setBackground(Color.red);
            jt_telephone.setBackground(Color.red);
            jt_address.setBackground(Color.red);
            jt_lastm.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"There is an issue to fill the table out");
        }
        
        this.setTitle("Information of "+ customer_name + " and Session of :" + user);
        
        try{
            Connection cn=Connect.Cnnct();
            PreparedStatement ps=cn.prepareStatement("select id_equipo,tipo_equipo,marca,estatus from equipos where id_cliente='" + ID +"'");
            ResultSet rs=ps.executeQuery();
            
            jtable=new JTable(model);
            jScrollPane1.setViewportView(jtable);
            
            model.addColumn("ID Equipo");
            model.addColumn("Tipo de Equipo");
            model.addColumn("Marca");
            model.addColumn("Estatus");
            
            while(rs.next()){
               Object table[]=new Object[4]; 
               for(int i=0;i<4;i++){
                   table[i]=rs.getObject(i+1);
               }
               model.addRow(table);
            }
            cn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"There is an issue to fill the table out");
        }
        
        jtable.addMouseListener( new MouseAdapter(){
            @Override
            public void mouseClicked (MouseEvent e){
                int row_table=jtable.rowAtPoint(e.getPoint());
                int column_table=0;
                
                if(row_table>-1){
                    id_device=(Integer)jtable.getValueAt(row_table,column_table);
                    new Device_information().setVisible(true);
                }
            }
        });
    }
    @Override
    public Image getIconImage(){
    
    Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
    return retValue;        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_title = new javax.swing.JLabel();
        jl_name = new javax.swing.JLabel();
        jt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_email = new javax.swing.JTextField();
        jt_telephone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_lastm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_title.setForeground(new java.awt.Color(255, 255, 255));
        jl_title.setText("CUSTOMER INFORMATION");
        getContentPane().add(jl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        jl_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_name.setForeground(new java.awt.Color(255, 255, 255));
        jl_name.setText("NAME:");
        getContentPane().add(jl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, -1));
        getContentPane().add(jt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EM@IL:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TELEPHONE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));
        getContentPane().add(jt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, -1));
        getContentPane().add(jt_telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, -1));
        getContentPane().add(jt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LAST MODIFICATION:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, -1));
        getContentPane().add(jt_lastm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 140, -1));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, 160));

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN DEVICE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));

        jButton2.setBackground(new java.awt.Color(51, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE CUSTOMER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));
        getContentPane().add(jl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
        Date date = new Date(); 
        try{
            Connection cn=Connect.Cnnct();
            PreparedStatement ps=cn.prepareStatement("update clientes set nombre_cliente=?,mail_cliente=?,tel_cliente=?,dir_cliente=?,ultima_modificacion=? where id_cliente='"+ID+"'");
            ps.setString(1, jt_name.getText().trim());
            ps.setString(2,  jt_email.getText().trim());
            ps.setString(3, jt_telephone.getText().trim());
            ps.setString(4, jt_address.getText().trim());
            ps.setString(5, formatter.format(date));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully updated!");
            cn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"There is an issue please try again!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Sign_device().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Document doc=new Document();    
        
        try{
            String route=System.getProperty("user.home");
            PdfWriter.getInstance(doc,new FileOutputStream(route+"/Desktop/"+jt_name.getText().trim()+".pdf"));
            
            com.itextpdf.text.Image header= com.itextpdf.text.Image.getInstance("src/images/BannerPDF.jpg");
            header.scaleToFit(650,1000);
            header.setAlignment(Chunk.ALIGN_CENTER);
            
            Paragraph prrf=new Paragraph();
            prrf.setAlignment(Paragraph.ALIGN_CENTER);
            prrf.add("Information of Customer \n\n");
            prrf.setFont(FontFactory.getFont("Tahoma",14,Font.BOLD,BaseColor.DARK_GRAY));
            
            doc.open();
            doc.add(header);
            doc.add(prrf);
            
            PdfPTable ptable=new PdfPTable(5);
            ptable.addCell("ID");
            ptable.addCell("Name");
            ptable.addCell("Em@il");
            ptable.addCell("Telephone");
            ptable.addCell("Address");
            
             try{
                 Connection cn=Connect.Cnnct();
                 PreparedStatement ps=cn.prepareStatement("select * from clientes where id_cliente='"+ID+"'");
                 ResultSet rs=ps.executeQuery();
                 
                 if(rs.next()){
                     do{
                         ptable.addCell(rs.getString(1));
                         ptable.addCell(rs.getString(2));
                         ptable.addCell(rs.getString(3));
                         ptable.addCell(rs.getString(4));
                         ptable.addCell(rs.getString(5));
                     }
                     while(rs.next());
                     doc.add(ptable);
                 }
                 
            Paragraph prrf2=new Paragraph();
            prrf2.setAlignment(Paragraph.ALIGN_CENTER);
            prrf2.add("Information of Sold Devices \n\n");
            prrf2.setFont(FontFactory.getFont("Tahoma",14,Font.BOLD,BaseColor.DARK_GRAY));
            
            doc.add(prrf2);
            
            PdfPTable ptable2= new PdfPTable(4);
            ptable2.addCell("ID Device");
            ptable2.addCell("Class of Device");
            ptable2.addCell("Mark");
            ptable2.addCell("Status");
            
            try{
                Connection cn2=Connect.Cnnct();
                PreparedStatement ps2=cn2.prepareStatement("select id_equipo,tipo_equipo,marca,estatus from equipos where id_cliente='"+ID2+"'");
                ResultSet rs2=ps2.executeQuery();
                
                if(rs2.next()){
                    do{
                     ptable2.addCell(rs2.getString(1));
                     ptable2.addCell(rs2.getString(2));
                     ptable2.addCell(rs2.getString(3));
                     ptable2.addCell(rs2.getString(4));
                    }
                    while(rs2.next());
                    doc.add(ptable2);
                }
            }
            catch(SQLException e){
                  JOptionPane.showMessageDialog(null,"There is a problem to fill out the information"); 
             
            }
            
                 
             }
             catch(SQLException e){
                 JOptionPane.showMessageDialog(null,"There is a inconvenient to fill out the information"); 
             }
             doc.close();
             JOptionPane.showMessageDialog(null,"File was generated!"); 
            
        }
        
        catch(Exception e){
         JOptionPane.showMessageDialog(null,"");   
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_name;
    private javax.swing.JLabel jl_title;
    private javax.swing.JLabel jl_wallpaper;
    private javax.swing.JTextField jt_address;
    private javax.swing.JTextField jt_email;
    private javax.swing.JTextField jt_lastm;
    private javax.swing.JTextField jt_name;
    private javax.swing.JTextField jt_telephone;
    private javax.swing.JTable jtable;
    // End of variables declaration//GEN-END:variables
}
