/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import Classes.Connect;

/**
 *
 * @author dsoto
 */
public class Sign_user extends javax.swing.JFrame {

    String user="";
    
    
    
    public Sign_user() {
        initComponents();
        setSize(650,430);
        setResizable(true);
        this.setLocationRelativeTo(null);
        
        user=Logo.user;
        setTitle("Administrator - Sesion of  " + user);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ImageIcon wallpaper= new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon ic=new ImageIcon(wallpaper.getImage().getScaledInstance(jl_wallpapper.getWidth(), jl_wallpapper.getHeight(),Image.SCALE_DEFAULT));
        jl_wallpapper.setIcon(ic);
        this.repaint();
        
   
    }
     @Override
    public Image getIconImage(){
    
    Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
    return retValue;        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_user_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        c_permission = new javax.swing.JComboBox<>();
        button_sign_user = new javax.swing.JButton();
        jl_wallpapper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN USER");
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-MAIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PERMISSIONS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txt_tel.setBackground(new java.awt.Color(153, 153, 255));
        txt_tel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_tel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        txt_user_name.setBackground(new java.awt.Color(153, 153, 255));
        txt_user_name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_user_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txt_name.setBackground(new java.awt.Color(153, 153, 255));
        txt_name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USERNAME:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        txt_email.setBackground(new java.awt.Color(153, 153, 255));
        txt_email.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, -1));

        txt_password.setBackground(new java.awt.Color(153, 153, 255));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setText("jPasswordField1");
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telephone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        c_permission.setBackground(new java.awt.Color(153, 153, 255));
        c_permission.setForeground(new java.awt.Color(255, 255, 255));
        c_permission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Taker", "Technician" }));
        c_permission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_permissionActionPerformed(evt);
            }
        });
        getContentPane().add(c_permission, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        button_sign_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        button_sign_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sign_userActionPerformed(evt);
            }
        });
        getContentPane().add(button_sign_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 120, 110));
        button_sign_user.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jl_wallpapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_sign_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sign_userActionPerformed
        
        int perm_cmb,validation=0;
        String name,mail,telephone,username,pass,perm_string="";
        
        name=txt_name.getText().trim();
        mail=txt_email.getText().trim();
        telephone=txt_tel.getText().trim();
        username=txt_user_name.getText().trim();
        pass=txt_password.getText().trim();
        perm_cmb=c_permission.getSelectedIndex()+1;
        
        if(name.equals("")){
            txt_name.setBackground(Color.red);
            validation++;
        }
        if(mail.equals("")){
            txt_email.setBackground(Color.red);
            validation++;
        }
        if(telephone.equals("")){
            txt_tel.setBackground(Color.red);
            validation++;
        }
        if(username.equals("")){
            txt_user_name.setBackground(Color.red);
            validation++;
        }
        if(pass.equals("")){
            txt_password.setBackground(Color.red);
            validation++;
        }
        
        
        if(perm_cmb==1){
          perm_string="Administrador";
        } else if(perm_cmb==2){
          perm_string="Taker";  
        } else if(perm_cmb==3){
          perm_string="Technician";  
        }
        
       try{
         Connection cn=DriverManager.getConnection("jdbc:mysql://localhost/db_project","root","");
         PreparedStatement ps=cn.prepareStatement("select username from usuarios where username='" +username+"'");
         ResultSet rs=ps.executeQuery();
         if(rs.next()){
             txt_user_name.setBackground(Color.red);
             JOptionPane.showMessageDialog(null, "Username exists please  try to user another Username");
         }
         else{
             cn.close();
             
             if(validation==0){
                 try{
                   Connection cn2=Connect.Cnnct();
                   PreparedStatement ps2=cn2.prepareStatement("insert into usuarios values (?,?,?,?,?,?,?,?,?)");
                   
                   ps2.setInt(1, 0);
                   ps2.setString(2,txt_name.getText().trim());
                   ps2.setString(3,txt_email.getText().trim());
                   ps2.setString(4,txt_tel.getText().trim());
                   ps2.setString(5,txt_user_name.getText().trim());
                   ps2.setString(6,txt_password.getText().trim());
                   ps2.setString(7,perm_string);
                   ps2.setString(8, "Activo");
                   ps2.setString(9, user);
                   
                   ps2.executeUpdate();
                   cn2.close();
                   Limpiar();
                   txt_name.setBackground(Color.green);
                   txt_email.setBackground(Color.green);
                   txt_tel.setBackground(Color.green);
                   txt_name.setBackground(Color.green);
                   txt_name.setBackground(Color.green);
                   
                   JOptionPane.showMessageDialog(null, "Successful register!");
                   this.dispose();
                   
                 }
                 catch(SQLException e){
                     JOptionPane.showMessageDialog(null, "Error to sign up this user please contact with your System Manager");
                 }
             }
             else{
                 JOptionPane.showMessageDialog(null, "You must complete all the fields");
             }
         }
         
         
       } 
       catch(SQLException e){
           System.out.println("Username unable please contact with  your system manager" + e);
       }
      
      
    }//GEN-LAST:event_button_sign_userActionPerformed

    private void c_permissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_permissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_permissionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_sign_user;
    private javax.swing.JComboBox<String> c_permission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jl_wallpapper;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_user_name;
    // End of variables declaration//GEN-END:variables
  public void Limpiar(){
      txt_name.setText("");
                   txt_email.setText("");
                   txt_tel.setText("");
                   txt_name.setText("");
                   txt_name.setText("");
                   c_permission.setSelectedIndex(0);
  }
}
