/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import Classes.Connect;
import javax.swing.JOptionPane;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.io.FileOutputStream;
/**
 *
 * @author dsoto
 */
public class Taker extends javax.swing.JFrame {
    String user;
    int user_sesion;
    /**
     * Creates new form Taker
     */
    public Taker() {
        initComponents();
        user=Logo.user;
        user_sesion=Administrator.user_sesion;
        setTitle("Taker " + " Session of  :" + user);
        setSize(550, 300);
        
        setResizable(true);
        this.setLocationRelativeTo(null);
        if(user_sesion==1){
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); }
        else{
          setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
        }
        ImageIcon wallpaper= new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon ic=new ImageIcon(wallpaper.getImage().getScaledInstance(jl_wallpaper.getWidth(), jl_wallpaper.getHeight(),Image.SCALE_DEFAULT));
        jl_wallpaper.setIcon(ic);
        this.repaint();
        
        try{
        Connection cn=Connect.Cnnct();
        PreparedStatement ps=cn.prepareStatement("select nombre_usuario from usuarios where username='" +user +"'"); 
        ResultSet rs=ps.executeQuery();
          if(rs.next()){
            jl_user.setText(rs.getString("nombre_usuario"));
          }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "There is a problem to find the username out");
        }
        
    }
    @Override
    public Image getIconImage(){
    
    Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
    return retValue;        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_user = new javax.swing.JLabel();
        jb_scustomer = new javax.swing.JButton();
        jb_mcustomer = new javax.swing.JButton();
        jb_pcustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("WELCOME :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, -1));

        jl_user.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        jb_scustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jb_scustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_scustomerActionPerformed(evt);
            }
        });
        getContentPane().add(jb_scustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jb_mcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        jb_mcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(jb_mcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jb_pcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jb_pcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(jb_pcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel2.setText("Sign Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setText("Manage Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel4.setText("Print Customer ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));
        getContentPane().add(jl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_scustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_scustomerActionPerformed
        new Sign_customer().setVisible(true);
    }//GEN-LAST:event_jb_scustomerActionPerformed

    private void jb_mcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mcustomerActionPerformed
        new LOG_USER().setVisible(true);
    }//GEN-LAST:event_jb_mcustomerActionPerformed

    private void jb_pcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pcustomerActionPerformed
        Document doc =new Document();
        
        try{
            String route=System.getProperty("user.home");
            PdfWriter.getInstance(doc,new FileOutputStream(route+"/Desktop/"+"CustomerList"+".pdf"));
            com.itextpdf.text.Image header= com.itextpdf.text.Image.getInstance("src/images/BannerPDF.jpg");
            header.scaleToFit(650,1000);
            header.setAlignment(Chunk.ALIGN_CENTER);
            
            Paragraph prrf=new Paragraph();
            prrf.setAlignment(Paragraph.ALIGN_CENTER);
            prrf.add("----------Customer List--------------- \n\n");
            prrf.setFont(FontFactory.getFont("Tahoma",14,Font.BOLD,BaseColor.DARK_GRAY));
            
            doc.open();
            doc.add(header);
            doc.add(prrf);
            
            PdfPTable ptable=new PdfPTable(5);
            ptable.addCell("ID");
            ptable.addCell("Name");
            ptable.addCell("Em@il");
            ptable.addCell("Telephone");
            ptable.addCell("Address");
            
            try{
                 Connection cn=Connect.Cnnct();
                 PreparedStatement ps=cn.prepareStatement("select id_cliente,nombre_cliente,mail_cliente,tel_cliente,dir_cliente from clientes ");
                 ResultSet rs=ps.executeQuery();
                 
                 if(rs.next()){
                     do{
                         ptable.addCell(rs.getString(1));
                         ptable.addCell(rs.getString(2));
                         ptable.addCell(rs.getString(3));
                         ptable.addCell(rs.getString(4));
                         ptable.addCell(rs.getString(5));
                     }
                     while(rs.next());
                     doc.add(ptable);
                 }
                 
                 JOptionPane.showMessageDialog(null,"File was successfuly generated!");
        }
        catch(SQLException e){
                JOptionPane.showMessageDialog(null,"There is an error to fill the PDF table out!");
        }
         doc.close();
    }//GEN-LAST:event_jb_pcustomerActionPerformed
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"An error pops up please try again!");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jb_mcustomer;
    private javax.swing.JButton jb_pcustomer;
    private javax.swing.JButton jb_scustomer;
    private javax.swing.JLabel jl_user;
    private javax.swing.JLabel jl_wallpaper;
    // End of variables declaration//GEN-END:variables
}
